### ISSUE TITLE
Possible bug with syncing temperatures

### ISSUE THREAD

**Issue by andreievg** [openmsupply/msupply-cold-chain#11]
#### To be investigated

- Left 3 sensors in the fridge and tablet outside for the night.
- Tablet was on charge and app open
- `issue 1` tablet switched of
- In the morning turned the app back on, all three sensors had 13 hours of data to be synced, they all looked pretty much like sensor this:

![Screen Shot 2021-01-20 at 2 24 10 PM](https://user-images.githubusercontent.com/26194949/105114169-32447280-5b2b-11eb-94dc-834655f8f584.png)

- First two sensors synced quite quickly
- Third sensor said 13 hours to sync
- Took all sensors out of the fridge
- `issue 2` Looks like Third sensor on the tablet started to adjust to new temperature of sensor, but it looks like it was attaching temperature logs to the tail end of the logs for the sensor (rather then current date/time) and continued showing that 13 hours to sync

Sensor 1 log export:
[sensor 1.zip](https://github.com/openmsupply/msupply-cold-chain/files/5839589/sensor.1.zip)
Sensor 2 log export:
[sensor 2.zip](https://github.com/openmsupply/msupply-cold-chain/files/5839592/sensor.2.zip)
Sensor 3 log export:
[sensor 3.zip](https://github.com/openmsupply/msupply-cold-chain/files/5839595/sensor.3.zip)
And screenshot:
![Screenshot_2021-01-20-09-24-54-840](https://user-images.githubusercontent.com/26194949/105114471-d4645a80-5b2b-11eb-904c-e1a5e0aaedc7.jpeg)

**Comment by joshxg** [comment]
Have adjusted the timestamp calculation which I believe fixes the issue here
