### ISSUE TITLE
When changing the orientation of a device the chart isn't resized quick enough

### ISSUE THREAD

**Issue by josh-griffin** [openmsupply/msupply-cold-chain#113]
**Describe the bug**
When changing the orientation of a device the chart isn't resized quick enough

**To Reproduce**

**Expected behavior**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mark-prins** [comment]
Decided on low priority as I don't think normal users often do this - it's an issue which is more noticeable when developing.

**Comment by adamdewey** [comment]
Agree with Mark, let's not support landscape for now, closing
