### ISSUE TITLE
Sorting columns should be debounced

### ISSUE THREAD

**Issue by joshxg** [openmsupply/msupply-cold-chain#117]
**Describe the bug**
Currently when you sort a row, you can spam click it and it causes all sorts of trouble!

Debounce it to avoid that

**To Reproduce**

**Expected behavior**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ArpitaSussol** [comment]
Tested in ColdChain V0.3.0

- [x] Sorting column is working accordingly.
