### ISSUE TITLE
Difficult to review breach configuration 

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/msupply-cold-chain#119]
**Is your feature request related to a problem? Please describe.**

Currently when looking at the config, I can only see all the config numbers by navigating into each of the 4 settings. This seems a few more steps for what could be one.

![Screenshot_2021-05-11-16-58-24-814](https://user-images.githubusercontent.com/7684221/117760956-a2ae0580-b27a-11eb-8705-01bce0d1a5f7.jpeg)

**Describe the solution you'd like**

2 Ideas, I'd probably lean towards the first:
1. Each configuration row has a subheader that just says `Temperature: x, duration y`. This would I would think is a simple enhancement so that I can see the config from one spot without a drastic rearrangement
2. Something closer to how I recall mobile's config for this. No deeper navigation, just all the fields exposed for each one on the one page.

**Describe alternatives you've considered**
n/a obvs more ideas are welcome!

**Additional context**

Coldchain docs: https://docs.msupply.foundation/en:cold_chain:settings
Mobile docs for comparison: https://docs.msupply.foundation/en:mobile:user_guide:vaccine

**Comment by joshxg** [comment]
related: https://github.com/openmsupply/msupply-cold-chain/issues/22

Personally I think the extra step isn't a big deal and makes the ui consistent [This does not mean that the settings UI could not be changed to actually be good, just that I prefer consistency over different for minor improvement].

I do think the sub text is a good idea so will implement that for this issue.

**Comment by joshxg** [comment]
#167

**Comment by ArpitaSussol** [comment]
Tested in ColdChain V0.3.0

- [x] Each configuration row has a sub-header that just says Temperature: x, duration y.
