### ISSUE TITLE
Laird BT510 check

### ISSUE THREAD

**Issue by andreievg** [openmsupply/msupply-cold-chain#12]
I had a bit of a play around:

[Laird Check.zip](https://github.com/openmsupply/msupply-cold-chain/files/5845641/Laird.Check.zip)

lairdNoble (can run with mac, `npm install && node lairdNoble.js`)

laridAndroid.java, needs:
```
 <uses-permission android:name="android.permission.BLUETOOTH" />
 <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
 <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
 <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
```

Both just find BT510 named device, and send `{"jsonrpc": "2.0", "method": "readLog", "params": [500], "id": 2}` and wait for reply and log it (for Android Logcat and filter by `laird`)

#### Pairing

Couldn't pair pragmatically (without user input):

* `setPairingConfirmation` requires BLUETOOTH_PRIVILEGED permission, which is only allowed for system apps.
*  `setPin` in combination with intercepting bond state intent action (via BroadcastReceiver and registerReceiver) didn't work for me. You can seee the commented out code line 126 to 155 in lairdAndroid

Looks like device doesn't restrict to communication from single paired device (i.e. once paired, can connect with mac and android to the same device without further user input, of course not at the same time).

#### Speed

Seems quick. Doesn't disconnect after sending message, unlike blue maestro (which i think is good, since multiple commands need to be issued to fully sync events). Thus need to listen for delimiter `}` to know message is received (would definitely want to use delimiter vs waiting for connection timeout to determine when message is complete and received)

**Comment by mark-prins** [comment]
Currently in discussions with a developer who might implement connectivity for this sensory.

**Comment by adamdewey** [comment]
@mark-prins, @andreievg - just having a cold chain tidy-up, can we close this?

**Comment by mark-prins** [comment]
thanks @adamdewey
