### ISSUE TITLE
Device battery level incorrect (0%) on charging start/stop

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/msupply-cold-chain#120]
**Describe the bug**

The battery level incorrectly goes to 0 when either unplugging or plugging in charger. You can get it working again by closing the app completely and reopening it.

![Screenshot_2021-05-11-16-58-24-814](https://user-images.githubusercontent.com/7684221/117773461-713e3580-b28c-11eb-9e5d-8e0a9fea843b.jpeg)
![Screenshot_2021-05-11-17-37-05-812](https://user-images.githubusercontent.com/7684221/117773472-74392600-b28c-11eb-81cc-8e750d9f7025.jpeg)

**To Reproduce**

1. Open the app
2. See battery percentage
3. Plug in charger: battery percentage goes to no value (possibly a hint at problem here! You'd think it'd be "0" if that was the case, I suspect it's nullish)
4. Restart app: see charging icon and correct percentage
5. unplug charger: battery percentage goes to no value

**Expected behaviour**
That battery and charging states update correctly.

**Smartphone (please complete the following information):**
 - Device: lenovo tab 10 TB-X304L
 - OS: Android 8.1
 - Version: 0.3.0-rc4

**Additional context**
I haven't gone this far in testing, but possible that battery state isn't updating at all (e.g. if it's on charge, does it actually update with increased battery?

**Comment by joshxg** [comment]
The hook from the library being used returns a pretty inconsistent value so have made a new hook to handle this
