### ISSUE TITLE
App crashes if you revoke location and/or storage permissions

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/msupply-cold-chain#123]
**Describe the bug**

If I revoke the permission while the app is running in background, it crashes when I resume focus

**To Reproduce**
1. Open app
2. give permissions if it doesn't already have them
3. Go to settings app, revoke permissions for mSupply ColdChain
4. Go back to mSupply ColdChain - it crashes

**Expected behavior**
Does not crash, just prompts user again for permissions

**Smartphone (please complete the following information):**
 - Device: Lenovo Tab 10 TB-X304L
 - OS: Android 8.1
 - Version: 0.0.3-rc4

**Additional context**
Similar to #64

**Comment by joshxg** [comment]
Turns out the android OS can sometimes kill the activity of the app which, when it comes back into the foreground trying to restore it crashes

https://github.com/software-mansion/react-native-screens/issues/17

**Comment by Chris-Petty** [comment]
Well ain't that neat! Just to confirm, is this closed 'cause you fixed it or 'cause fighting the OS is futile?

**Comment by joshxg** [comment]
Sorry, no, I fixed it by having the activity reload rather than trying to recreate it. I.e. when you changing the permissions after going to settings and go back to the app, the app gonna restart

**Comment by ArpitaSussol** [comment]
Tested in ColdChain 0.3.0

## Testing

- [x] Open app
- [x] give permissions if it doesn't already have them
- [x] Go to settings app, revoke permissions for mSupply ColdChain
- [x] Go back to mSupply ColdChain - it should not crash
