### ISSUE TITLE
TESTING: Download and emailing

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/msupply-cold-chain#129]
# Temperature breaches tests

This suite contains tests around downloading and emailing of sensor data.

## Setup

- Have the app 
- Have some sensors. Probably don't want them configured just yet

### Consecutive breaches

- [ ] Add a sensor, set start logging time for 5 minutes from now
- [ ] Sensors > sensor detail > Download data button
  - [ ] User is prompted to enter username and comment. Username is mandatory before OK button is enabled
  - [ ] Download button attempts to start download
  - [ ] While the sensor has no logs, you cannot download the logs
  - [ ] Once the sensor has logs, you can download the logs
  - [ ] Logs go to folder `downloads/cce`
  - [ ] Log file name format is very very nice
  - [ ] Log data downloaded is correct
  - [ ] User name and comment are included
  - [ ] Downloading a log from a sensor, then doing it again really quickly, does not overwrite the last file downloaded from app (losing the log data!).
- [ ] Settings > Sensor settings > Some available sensor > Download
  - [ ] It downloads the data just like above
- [ ] Sensors > Sensor detail > Email data button
  - [ ] User is prompted to enter username and comment. Username is mandatory before OK button is enabled
  - [ ] Pressing OK prompts user to choose email client
  - [ ] Once email client is opened, an email is populated with attached log file

**Comment by Chris-Petty** [comment]
@joshxg could you please have a pass over my tests and add/remove anything as you see fit?

`Settings > Sensor settings > Some available sensor > Download` doesn't seem to do anything. Might be redundat having two ways to get to app downloads anyway, so an easy fix is to remove the button 🕺

**Comment by joshxg** [comment]
That's great. Thanks a lot!

The settings > download button I believe triggers .. downloading/syncing/get logs from the sensor via bluetooth. It isn't really helpful because we passively try to do this every 1 minute, and it will short circuit `if (time.now < lastTemperatureLogTimestamp)`, so there's often a very small amount of time this will actually be useful. So i'll remove!

**Comment by joshxg** [comment]
One thing to potentially expand on is the 'data be right' and we could do some better definitions of what is in the report, I guess. But .. later

**Comment by adamdewey** [comment]
Leaving testing to the QA team..
