### ISSUE TITLE
0.0.2 upgrade to 0.0.3-rc7: No sensor interaction

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/msupply-cold-chain#132]
**Describe the bug**
Installed 0.0.2 and added 2 sensors. Gathered some logs. Upgraded to 0.0.3-rc7. Sensors no longer have any interaction. Restarting the app does not fix it.

![Screenshot_2021-05-15-12-53-07-132](https://user-images.githubusercontent.com/7684221/118343461-4fd79500-b57d-11eb-9e5e-9dc0a04abe5a.jpeg)

**To Reproduce**
1. Install 0.0.2
2. Add sensors
3. Get some logs
4. Upgrade to 0.0.3-rc7
5. bork UI

**Expected behavior**

The sensors look how they should. 

**Smartphone (please complete the following information):**
 - Device: Lenovo tab 10 
 - OS: Android 8.1
 - Version 0.0.2->0.0.3-rc7

**Additional context**

Renaming the sensor doesn't make UI refresh and fix it self. Does get the new name though.

**Comment by joshxg** [comment]
Weird..

Can you be more specific with "no interaction"..?

Obviously the sensor status box is gone, but are logs being downloaded? Or you just can't tell?

**Comment by joshxg** [comment]
Done an rc8 with a fix for this

**Comment by Chris-Petty** [comment]
Tested, fixed in 0.0.3-rc9
