### ISSUE TITLE
gaps in charts when there are no logs

### ISSUE THREAD

**Issue by josh-griffin** [openmsupply/msupply-cold-chain#134]
**Is your feature request related to a problem? Please describe.**
At the moment there is no gap created in the line chart where there were no logs.. it will just connect from dot to dot.

We should updated the query such that we receive `null` when there is a gap of temperatures

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by adamdewey** [comment]
Hopefully we don't ever get any gaps from the sensors! So closing
