### ISSUE TITLE
Default log interval not working

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/msupply-cold-chain#135]
**Describe the bug**

When I install the app and start setting up sensors, I set the log interval from 5 to 1. When I add sensors, they still get 5.

Not sure if related, but when I reopen the app, the Logging interval I set is not remembered, it has returned to 5.

**To Reproduce**

1. Install app
2. Go to settings
3. Set Logging interval to 1
4. Add a sensor
5. Check the log interval in the added sensor. It is 5 rather than 1.

**Expected behavior**

**Smartphone (please complete the following information):**
 - Device: Lenovo tab 10
 - OS: Android 8.1
 - Version 0.1.0

**Comment by Chris-Petty** [comment]
I reckon fair to be high, makes config a bit of a pain!

**Comment by ArpitaSussol** [comment]
Tested in V0.3.0

## Testing

- [x] Install app
- [x] Go to settings
- [x] Set Logging interval to 1
- [x]  Add a sensor
- [x] Check the log interval in the added sensor. It should be 1.
