### ISSUE TITLE
Display app version in app

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/msupply-cold-chain#139]
**Is your feature request related to a problem? Please describe.**
I upgraded a customers tablet from 0.0.2 to 0.1.1. They wanted to be able to tell it worked:

![image](https://user-images.githubusercontent.com/7684221/118732019-b1557780-b88d-11eb-88af-8a9093a8138d.png)

**Describe the solution you'd like**
Show the app version somewhere upfront in the app. Maybe under settings.

**Describe alternatives you've considered**
-

**Comment by ArpitaSussol** [comment]
Tested in ColdChain 0.3.0

## Testing

- [x] showing App Version under Settings under "ABOUT THIS APP" label
