### ISSUE TITLE
Tidy up mSupply guy

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/msupply-cold-chain#140]
**Is your feature request related to a problem? Please describe.**
The white patches on the mSupply icon look a bit rough. Ideally, update the icon and the splash screen

Splash screen is currently this:
![big-cold-guy-b4](https://user-images.githubusercontent.com/9192912/118763016-42970f00-b8cb-11eb-8cf2-971a93173a60.png)

**Describe the solution you'd like**
Make it pretty.

**Comment by joshxg** [comment]
https://github.com/openmsupply/msupply-cold-chain/issues/97

This one is also annoying.. stop going so big when rotated 😡
