### ISSUE TITLE
mSupply integration

### ISSUE THREAD

**Issue by joshxg** [openmsupply/msupply-cold-chain#142]
# mSupply integration tests

The context for this testing template is tests related to sending data from `mSupply ColdChain` to `mSupply Desktop`

## Setup

- Have a sensor connected with the app
- Setup the alternate server as per this doc: https://docs.google.com/document/d/1AeLKsfVB1ZwYPa81VylFtE97_KWNR0QJoNZdypKj4aw/edit

### Settings
- [ ] Can enter a username
- [ ] Can enter a password
- [ ] Can enter a url for temperature-breaches
- [ ] Can enter a url for temperature-logs
- [ ] Can enter a url for sensors
- [ ] Can enter a url for login
- [ ] When entering a valid login url, username and password you can click test connection and a toast message will tell you if the connection with the server was valid or not.

### Integration
- [ ] Whenever a temperature log is created, after a minute or so it will appear in mSupply
- [ ] Whenever a temperature breach is created, after a minute or so it will appear in mSupply
- [ ] Whenever a temperature breach is created, after a minute or so all of the temperature logs which should belong to the temperature breach should also be updated in mSupply
- [ ] Whenever a sensor is created, after a minute or so it will appear in mSupply
- [ ] Whenever a sensor is edited, after a minute or so it will appear in mSupply

**Comment by ArpitaSussol** [comment]
Tested in coldchain- 0.2.0-rc1
Testing:
- [x] Can enter a username
- [x] Can enter a password
- [x] Can enter a url for temperature-breaches
- [x] Can enter a url for temperature-logs
- [x]  Can enter a url for sensors
- [x] Can enter a url for login

**Comment by ArpitaSussol** [comment]
Tested in Coldchain-0.2.0-rc2 and mSupply V5-02-00 exe

## Integration

- [x] Whenever a temperature log is created, after a minute or so it will appear in mSupply
- [ ] Whenever a temperature breach is created, after a minute or so it will appear in 
- [ ] mSupplyWhenever a temperature breach is created, after a minute or so all of the temperature logs which should belong to the temperature breach should also be updated in mSupply
- [x] Whenever a sensor is created, after a minute or so it will appear in mSupply
- [ ] Whenever a sensor is edited, after a minute or so it will appear in mSupply
