### ISSUE TITLE
Can't update a sensors name

### ISSUE THREAD

**Issue by joshxg** [openmsupply/msupply-cold-chain#146]
**Describe the bug**
When trying to update a sensors name, it doesn't work!

**To Reproduce**
1. Go and try update a sensor name, apparently doesn't work!

**Expected behavior**

**Smartphone (please complete the following information):**

**Additional context**

Reported by Arpita

**Comment by ArpitaSussol** [comment]
Tested in ColdChain 0.3.0.rc0

##Testing

- [x] Go and try update a sensor name 
- [x] Sensor name should be updated.
