### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by josh-griffin** [openmsupply/msupply-cold-chain#147]
**Describe the bug**

There are a few areas which would be good to do a little bit of performance tuning.

From a purely 'user feel', the start times, navigating to the detail page and navigating in some of the settings pages don't feel the best.

- I have been unable to take a sampling profile to make a flame chart of performance bottle necks which is a big deal. I'm not sure exactly why, but when stopping the sampling, the app crashes and the sampling is an empty file.
- We have a lot of logging, which does help to indicate that some queries are taking a little too long. With some minor checking, the queries themselves on the native side are not taking very long so the issue is elsewhere. It does seem as though the queries are being executed in sequence and are blocking. I think there needs to be some investigation as to why this is as it seems to be one of the biggest problems ... but again, need to get profiling to work to really know!

**Comment by adamdewey** [comment]
Performance is good enough for now, not noticed issues as an end user, so closing
