### ISSUE TITLE
Crash when pressing back button from sensors page while app is navigating

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/msupply-cold-chain#150]
**Describe the bug**

App crashes to OS, shows dialog "mSupply ColdChain stopped working".

Probably: https://app.bugsnag.com/sustainable-solutions-nz-ltd/cce/errors/60ad9b31ccae9800073628bc?filters[event.since][0]=30d&filters[error.status][0]=open

**To Reproduce**
1. Open app
2. Go to settings
3. In quick order: tap sensors to go back to that overview, and while it's navigating press the back button

**Expected behavior**

Navigating finishes and app also gets put in background, doesn't crash.

**Smartphone (please complete the following information):**
 - Device: Samsung Tab A 10.1 2016
 - OS: android 8.1.0
 - Version: 0.2.0

**Comment by Chris-Petty** [comment]
Is it time to connect bugsnag to this repo? Do we find it useful for mobile, or is it mostly noisy? How do we keep tabs otherwise?

**Comment by joshxg** [comment]
Forgot to upload the source map for this latest version.

I don't mind having bugsnag issue integration on
