### ISSUE TITLE
Unacknowledged Temperature breaches shows inconsistent header in Server side

### ISSUE THREAD

**Issue by ArpitaSussol** [openmsupply/msupply-cold-chain#163]
**Describe the bug**
Unacknowledged Temperature breaches shows inconsistent header in Server side

**To Reproduce**
1. Setup store in msupply server
2. Setup Sensor, Temperature breach setting and sync setting in Cold Chain app
3. Check the server in case of Temperature breach occurs.
4. See error. Unacknowledged Temperature breaches Header is showing "Tomorrow at 12:00 AM".
![VirtualBox_Cold Chain Test_01_06_2021_15_53_19](https://user-images.githubusercontent.com/58979436/120312406-652c1d80-c2f8-11eb-84d7-1d60b23ce82c.png)

**Expected behavior**
Header should be related with current temperature breach timestamp.

**Smartphone (please complete the following information):**
 - Device: Samsung
 - OS: Android 8.1
 - Version 0.3.0.rc1

**Additional context**

**Comment by adamdewey** [comment]
Think this was perhaps in the early days of breach testing - feel free to open a new case if spotted again
