### ISSUE TITLE
Update battery normalisation range

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/msupply-cold-chain#174]
**Describe the bug**
The battery level reported by the blue maestro sensors doesn't match the stated range.
I ran a sensor until it stopped, and the last battery level I have is -16
The tablet also ran out of battery 🙄  so I'm not certain this is the lowest that the sensor will report.

![Screenshot_2021-06-05-10-01-06-500](https://user-images.githubusercontent.com/9192912/120868231-ae75b900-c5e7-11eb-9381-809593cc4423.jpeg)

My calculations give a min value of 71 not 75, assuming that -16 is in fact the minimum. 
Ideally we need to find another almost flat battery and try again.

**Comment by joshxg** [comment]
Argh! My bad..

![image](https://user-images.githubusercontent.com/35858975/120873657-24cde780-c5f7-11eb-8f70-19c478700a54.png)


From here: https://drive.google.com/drive/u/2/folders/1AlMQEGAhVio2q8ouPYK4IKlTI8ZQhDu1

**Comment by mark-prins** [comment]
sweet, so 70-100 is probably a good range then
