### ISSUE TITLE
Reduce number of configuration URLs the user must enter from 4 to 1

### ISSUE THREAD

**Issue by npendergrast** [openmsupply/msupply-cold-chain#177]
**Is your feature request related to a problem? Please describe.**
Currently the user must enter 4 URLs to sync all required temp data to the mSupply desktop api. This is mucho annoying!! There is a lot of room for error and also there is no indication if you have entered them correctly as the Test Connection button only tests the Login URL and credentials.

**Describe the solution you'd like**
1 config url

**Describe alternatives you've considered**

**Additional context**

**Comment by adamdewey** [comment]
Done!!
