### ISSUE TITLE
Tablet battery level incorrect

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/msupply-cold-chain#194]
**Describe the bug**
My battery shows as 21%
Closing the app and checking the value on the tablet, shows a value of 98%
The charging indication changes when I plug the tablet in, but the battery percentage doesn't.

![Screenshot_2021-06-24-09-07-07-630](https://user-images.githubusercontent.com/9192912/123176570-cac69080-d4d7-11eb-8172-858dfe93c170.jpeg)

![Screenshot_2021-06-24-09-06-41-336](https://user-images.githubusercontent.com/9192912/123176585-cf8b4480-d4d7-11eb-8e9d-ff6597305688.jpeg)

**To Reproduce**
Steps to reproduce the behaviour:
1. Look at the battery percentage

**Expected behaviour**
I'll leave this up to you to figure out.

**Comment by joshxg** [comment]
Ha.

I guess.. I just didn't even read the docs.

https://docs.expo.io/versions/latest/sdk/battery/#batteryaddbatterylevellistenercallback

This method doesn't do what I assumed it did (callback on every battery level change..)
