### ISSUE TITLE
AndroidManifest.xml does not appear to be set up like the recommendations in react-native-ble-plx

### ISSUE THREAD

**Issue by chetstone** [openmsupply/msupply-cold-chain#196]
**Describe the bug**
Is this intentional?

**Additional context**
https://github.com/dotintent/react-native-ble-plx#android-example-setup

https://github.com/openmsupply/msupply-cold-chain/blob/master/android/app/src/main/AndroidManifest.xml

**Comment by joshxg** [comment]
Oh, interesting!

It's certainly not intentional. It seems we're using `COARSE_LOCATION` rather than `FINE_LOCATION`.

Having a look at the docs, seems we need to be using `FINE_LOCATION` from android 9+ ..! 

The `uses-feature` flag seems to be primarily for the play store, which we aren't on.

**Comment by katherine-sussol** [comment]
Closed by #199 (`FINE_LOCATION` portion only)
