### ISSUE TITLE
Can't see sensors when using Android 10

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/msupply-cold-chain#199]
**Describe the bug**
Sensors do not show when using the app on Android 10 and so cannot be connected. 

**To Reproduce**
1. Install app on Android 10
2. Attempt to add sensor

![2021-09-21 19 55 11](https://user-images.githubusercontent.com/19318937/134133540-ff1b1266-d02d-45a8-80df-3656d00b0876.jpg)

**Expected behavior**
Sensor appears

**Smartphone (please complete the following information):**
 - Device: Lenovo TB-X505N 
 - OS: Android 10
 - Version 0.4.0

**Additional context**

**Comment by katherine-sussol** [comment]
So I'm not 100% sure if it will fix it (maybe I should have taken up the offer for an Android 10 tablet 😆 )... but have applied the change that fixed a similar issue in mobile in #202

**Comment by katherine-sussol** [comment]
Fixed by #202

**Comment by adamdewey** [comment]
Nice Kat!
