### ISSUE TITLE
App freezes after 5 or 6 hours continuous use

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/msupply-cold-chain#200]
**Describe the bug**

Have set up a tablet to monitor my fridge. Tablet is dedicated to Cold Chain app only. 

App is set to run with screen always on and displaying Cold Chain. 

After 5 or 6 hours the app freezes and becomes non-responsive. This has happened twice in a row. 

**To Reproduce**
1. Set tablet to never sleep
2. Install app
2. Add sensors (I have 3 sensors)
3. Leave tablet on main temperature monitoring screen for a few hours

**Expected behavior**
App to continuously operate until civilisation itself decays. 

**Smartphone (please complete the following information):**
 - Device: Lenovo TB-X505N
 - OS: Android 9
 - Version 0.4.0

**Additional context**

**Comment by katherine-sussol** [comment]
Fixed by #203
