### ISSUE TITLE
4 hours of logs missing

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/msupply-cold-chain#201]
**Describe the bug**

4 hours worth of sensor logs are missing from the app. This applies to all 3 sensors. 

The app should have been running continuously the whole time, and neither the tablet nor sensors have moved locations. 

Nothing else has happened to the tablet / sensors in the meantime. 

Possibly related to https://github.com/openmsupply/msupply-cold-chain/issues/200, but also possibly not as I've seen 2 crash / freezes but only 1 lot of missing logs. 

![photo_2021-09-21 20 55 51](https://user-images.githubusercontent.com/19318937/134142781-6d0b17ad-70ca-4e54-90f7-5cf287caadb2.jpeg)

**To Reproduce**
1. Unknown
2. Connect sensors and wait?

**Expected behavior**
All logs to be present and correct and to recover retrospectively, even if there was a crash of the app. 

**Smartphone (please complete the following information):**
 - Device: Lenovo TB-X505N
 - OS: Android 9
 - Version 0.4.0
 
**Additional context**

**Comment by adamdewey** [comment]
Have just discovered 2 more 4 - 5 hour gaps in the logs from last night. 

This time on 2 separate tablets connected to different sensors. 

The weird thing is the gap happens at exactly the same time on both tablets - possibly because I set them up and left them running at the same time?

![photo_2021-09-22 09 27 23](https://user-images.githubusercontent.com/19318937/134250128-0f1d82fa-5243-4c2d-8cc0-16af4782cf0d.jpeg)

![photo_2021-09-22 09 27 26](https://user-images.githubusercontent.com/19318937/134250115-336d4bb4-3a87-4853-9db6-22225e33a816.jpeg)

**Comment by adamdewey** [comment]
Some more test results: 

- 1 min logging = 0 hours missing logs
- 5 min logging = ~4 hours missing logs
- 10 min logging = ~8 hours missing logs 

![PXL_20210926_203040014](https://user-images.githubusercontent.com/19318937/134823281-43dc59d4-0194-40d7-98dc-7097d466b068.jpg)

**Comment by katherine-sussol** [comment]
Thanks for all the testing! Bit worrying 😢 

Seeing the same thing on my tablet with 5 min logging interval, 4 hour gaps (and it's across all sensors so more likely app related than sensor related...) 👀

**Comment by katherine-sussol** [comment]
Update: Seems like the logs aren't actually missing, it's just the history page doing some funky pagination, which results in logs 51-100 (consistently) 'appearing' missing

**Comment by adamdewey** [comment]
Seems good so far! Thanks Kat! :)
