### ISSUE TITLE
App stops syncing data after a couple of days on Android 11

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/msupply-cold-chain#206]
**Describe the bug**
After a couple of days (still need to identify exactly how long) the app stops syncing data to the server. 

![PXL_20211031_192702628](https://user-images.githubusercontent.com/19318937/139599333-f71931a3-b762-4d51-8d4f-2cb53c6587e3.jpg)

Restarting the app fixes the problem. 

![PXL_20211031_192937756](https://user-images.githubusercontent.com/19318937/139599334-959c0c0f-fd05-4f67-9b67-13db2b1fa244.jpg)

**To Reproduce**
1. Use Samsung Galaxy Tab A7 SM-T500
2. Set screen to always stay on (need to enable Developer settings and select in there)
3. Set app up with multiple sensors
4. Integrate the app with a server
5. Leave the app for a couple of days
6. Note that sync eventually stops

**Expected behavior**
Sync to keep running ad infinitum. 

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Tab A7 SM-T500
 - OS: Android 11
 - Version: 0.4.1

**Additional context**
I don't recall seeing this on Android 10 on the Lenovo tablets.

**Comment by chetstone** [comment]
I was seeing this too. Thought it was normal. I didn't have the app connected to a server but syncing with the BT sensors stops after a while.

**Comment by adamdewey** [comment]
@chetstone - oh interesting. Are you also using Android 11?

**Comment by chetstone** [comment]
Yes. It's an SM-T500 also.

**Comment by Chris-Petty** [comment]
@adamdewey Andrew may have hinted at this problem when we chatted to him, might not be exclusive to Android 11

**Comment by adamdewey** [comment]
@Chris-Petty - oh I must have missed that! 

I haven't seen this exact problem on those Lenovo Android 10 tablets if I leave the screen on 24/7 I don't think - but there may be some other variables between mine and his tablets I guess!

**Comment by katherine-sussol** [comment]
I've been running with this for a few days on Android 11 and haven't reproduced this week, but have been accidentally hitting various buttons on the screen (stray cables...), so wonder if it's specific to being on that main screen for a long time. Or maybe one of these presses inadvertently backgrounded the app 🤔 .

**Comment by adamdewey** [comment]
Hmm, yeah my guess is it needs to just be sitting there untouched for a while. Let me set mine up again and see how long it takes to bomb out...

**Comment by adamdewey** [comment]
Ok, have set my tablet up just now, will report back when/if it stops reporting...

**Comment by katherine-sussol** [comment]
> Ok, have set my tablet up just now, will report back when/if it stops reporting...

Oh awesome, thanks Adam! I've started my screen back up this morning around 10am too. I will get you, elusive 😡 🐛

**Comment by adamdewey** [comment]
Oops, forgot to update - mine crashed out 3 days ago!

So managed a good 5 days reporting first...

**Comment by adamdewey** [comment]
Just observed this on Android 10 too
![PXL_20220221_000211605](https://user-images.githubusercontent.com/19318937/154872929-ed7f9f64-0feb-48c0-949b-b29d467dce63.jpg)

An app restart rectified things

- Lenovo TB-X505N
- Android 10 
- No MEMDM
- 2 x Blue Maestro sensors in fridge
- 1 x Laird sensors in fridge
- 5 minute data sync interval
- Tablet about 10 metres from fridge

**Comment by katherine-sussol** [comment]
_Might_(??) be linked to https://app.bugsnag.com/sustainable-solutions-nz-ltd/cce/errors/615e397b45c36700076788cc?filters[event.since]=all&filters[app.release_stage]=production&filters[error.status]=open&event_id=6212f0680090891670d00000? Error sounds a bit gibberish atm (time to do some searching online 🤔 ) but seems consistent with the comment that there was a system dialog pop up before the error started happening.

![image](https://user-images.githubusercontent.com/65875762/154879987-e3f7bd1d-a886-4ce9-9f3e-cced8e0a0efb.png)

**Comment by adamdewey** [comment]
Also, Kat - don't look! Kiribati trumps all 😁

**Comment by mark-prins** [comment]
I think this is resolved with the UUID generation change - has been working for me for more than a week; and I have a reproducible scenario to create an issue. whether is it **the** issue or not, time will tell.

Closing this issue for now, and we can reopen if required. Note that production debug logging is now available, so we can diagnose on a long running tablet if required.
