### ISSUE TITLE
Export logs are not saved to device in Android 10 

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/msupply-cold-chain#207]
**Describe the bug**
Sensor export logs are not saved to the device when using Android 10 (Lenovo). 

Seems to work ok on Android 11 (Samsung): 

https://user-images.githubusercontent.com/19318937/139776006-445a42da-9f2d-424e-ad3e-33d82782a779.mp4

**To Reproduce**
1. Click into a sensor
2. Press the export button
3. Go try to find the exported file

**Expected behavior**
File to appear in the location indicated by the toast

**Smartphone (please complete the following information):**
 - Device: Lenovo X505N
 - OS: Android 10
 - Version 0.4.1-rc2

**Additional context**
This is causing issues for Cook Islands (also using Lenovo Android 10)

**Comment by katherine-sussol** [comment]
Closed by #208 (v0.4.2)

**Comment by adamdewey** [comment]
Nice work Kat! :)
