### ISSUE TITLE
When in meMDM kiosk mode you cannot enter bluetooth pairing pin for Laird Sensor

### ISSUE THREAD

**Issue by npendergrast** [openmsupply/msupply-cold-chain#213]
**Is your feature request related to a problem? Please describe.**
When a tablet is in meMDM kiosk mode it seems that you cannot enter a bluetooth pairing pin, which is required to connect a Laird temp sensor.

On a Lenovo device I can see a system notification for pairing with the sensor, however kiosk mode will not let me open the notification to enter the pin. I must first take the device out of kiosk mode before I can open the notification (which is not ideal for our clients that want the devices protected from misuse)

**Describe the solution you'd like**
The ability to enter the pairing pin in an app input field/window if this is possible

**Describe alternatives you've considered**

**Additional context**

**Comment by joshxg** [comment]
I think the issue here might be more that we need to actually enter a pairing key on a laird sensor at all!

**Comment by chetstone** [comment]
I'm not familiar with meMDM, but can you run a different app to do the pairing? You can use Laird's BT510 app to pair and once the sensor is paired with the tablet, it doesn't need to be re-paired to work with ColdChain or another app.

While developing, I found the BT510 app was very useful and it may be useful for people in the field as well. You can pair and set parameters that you can't access from ColdChain, and you can use it to upgrade firmware. About half the sensors that came in my shipment had old firmware and had to be upgraded. 

Speaking of upgrading firmware, my memory is a little hazy but I think I was actually unable to upgrade firmware using the BT510 app on my android tablet-- the installation kept hanging, and I worked around it by using my iPhone. 

I have no idea why passcode pairing is required on the Laird and not on Blue Maestro. I just did a quick scan of the Laird docs and there doesn't seem to any mention of a way to get around this. You can change the passkey (using the BT510 app) but I don't see a way to make it not required.

**Comment by adamdewey** [comment]
Decided not to support Laird at this time so closing
