### ISSUE TITLE
Main logging interval setting is confusing

### ISSUE THREAD

**Issue by GaryWilletts** [openmsupply/msupply-cold-chain#216]
**Is your feature request related to a problem? Please describe.**
Changing the logging interval on the main sensors page does not change the logging interval for the sensors. This is confusing!

**Describe the solution you'd like**
Either the label needs to change to accurately describe what this setting is (is it something like the default interval for new sensors?) or remove it. Do we really need the setting there?

**Describe alternatives you've considered**
Anything else you can think of.

**Additional context**
I don't use coldchain bery often but this gets me every time. I think this must be an irritation to all users.

**Comment by mark-prins** [comment]
Changed the title to `Default interval` - the subtext is already `The default logging interval for all new sensors` which describes correctly I think. Hopefully updating the title will catch the eye and change the focus of the title
