### ISSUE TITLE
Keyboard issue with 0.5.0-rc1

### ISSUE THREAD

**Issue by chetstone** [openmsupply/msupply-cold-chain#217]
**Describe the bug**
When I try to change the name of a sensor in landscape mode, and when I insert the cursor in the text box, the keyboard does not stay up. The problem does not exist in portrait mode.

**To Reproduce**
1. With the tablet in landscape mode, Go to Settings/Sensor
2. Choose a sensor
3. Touch Sensor name 
4. Touch somewhere in the text box
5. The keyboard will pop up momentarily on the screen, then disappear

**Expected behavior**
The keyboard should stay up allowing you to edit the name

**Smartphone (please complete the following information):**
 - Device: [Samsung Galaxy Tab SM-T500]
 - OS: [Android 11]
 - Browser [Chrome]

**Additional context**
Problem does not occur in Portrait mode

Also, when I download the APK in chrome, it asks me if I want to replace the app, saying "this will not change any of your data". However, it did delete my configuration. I had to reconnect to my sensors and the logs were gone.

(This is not a problem for me, since I'm not using the app for anything important)

I'm not sure if this is expected or not, I don't think I've ever tried to install an APK this way on android.

**Comment by mark-prins** [comment]
Thanks @chetstone! Good to hear from you 😄

**Comment by chetstone** [comment]
How're things down under Mark?

**Comment by mark-prins** [comment]
Wintery for us! good weather for sitting inside and looking at cold chain issues 😉 
And with you?

**Comment by mark-prins** [comment]
Note: fine on the older Lenovo I have

**Comment by adamdewey** [comment]
Just tidying up the backlog - not sure we want to support landscape as a use case so closing for now
