### ISSUE TITLE
BT510 pairing with Cold Chain App: suggestion for pin code is incorrect

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/msupply-cold-chain#225]
**Describe the bug**
BT510 pairing with Cold Chain App: suggestion for pin code is incorrect

**Expected behavior**
Should be 123456 and not 0000 or 1234

https://connectivity-staging.s3.us-east-2.amazonaws.com/2020-04/CS-GUIDE-BT510%20v1_4.pdf

(page 17)

**Comment by adamdewey** [comment]
Decided not to support Laird at this time so closing
