### ISSUE TITLE
Android 12: Application stops sending data to server after ~30 mins

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/msupply-cold-chain#226]
**Describe the bug**

When using Android 12 the application stops sending data to the server after roughly 30 mins. 

If the application is restarted the missing data is then sent to the server. 

This causes issues for all integration pieces: 
- Desktop alerts
- Dashboard
- Telegram alerts

![image](https://user-images.githubusercontent.com/19318937/201690001-0056a3ae-715f-41eb-b321-0f4506b7c9f3.png)

![image](https://user-images.githubusercontent.com/19318937/201690037-1926aeea-1c25-48a6-86a9-11af29794398.png)

**To Reproduce**
1. Start application recording 3 sensors on Android 12
2. Monitor integration with server

**Expected behavior**
Data to be sent continuously from application to server.

**Smartphone (please complete the following information):**
 - Device: Samsung Tab A7
 - OS: Android 12 (SP1A.210812.016.T500XXS4CVJ1)
 - ColdChain Version 0.5.0
 - Sensors: Blue Maestro (blue Tempo Disc 3)

**Additional context**
- 2 of the sensors are set to log every 2 mins
- 1 of the sensors is set to log every 1 min

**Comment by mark-prins** [comment]
unable to replicate so far. I have a release build running on a samsung android 12 and it hasn't stopped yet

**Comment by adamdewey** [comment]
@mark-prins - strange, is it 0.5.0 downloaded from the releases page?

**Comment by mark-prins** [comment]
I've made a new build, which has some logging around the sync calls.. so technically no. realistically though, it's the 5.0 branch and a release build, so is almost the same thing. I am running against a local mSupply instance though, so will change that and use a hosted server instead. Perhaps network performance is a problem?

**Comment by mark-prins** [comment]
@adamdewey which version of mSupply are you using? because I'm running locally, I'm on the sync-v5 branch. I should test with the version you are running. And are you running it locally, or is it a cloud server?

**Comment by adamdewey** [comment]
@mark-prins V6-04-00 

And yeah, it's a cloud server - it's the vaccine demo server. Details are under 'Vaccine and Cold Chain - Stable Demo Server' in BW :)
