### ISSUE TITLE
Coldchain Can't Send Log Files via Email

### ISSUE THREAD

**Issue by kahn-msupply** [openmsupply/msupply-cold-chain#245]
**Describe the bug**

When trying to send logs from Coldchain, you see a 'writing' message, which disappears, and you are brought back to same menu. Nothing happens.

**To Reproduce**
1. Open Coldchain 0.5.3
2. Click a sensor
3. Click mail icon to send log
4. See writing message quick appear and disappear

**Expected behavior**

If there is an issue display the issue, or open email client?

**Smartphone (please complete the following information):**
 - Device: Samsung Tablet A8
 - OS: Android 13
 - Browser: N/A
 - Version: 0.5.3

**Additional context**

Downloading logs to device works.

**Screenshots**

![image](https://github.com/openmsupply/msupply-cold-chain/assets/132425100/2c4c5f9f-01b9-4f30-920e-45d586c9565f)

**Comment by adamdewey** [comment]
This is an introduced bug since 0.5.3

We should fix it but in the meantime the workaround is to get data from the dashboard.

**Comment by adamdewey** [comment]
This has been fixed but there is still an issue with emailing logs, see #102

**Comment by AnushaUp** [comment]
This issue will be done and test [HERE](https://github.com/msupply-foundation/msupply-cold-chain/issues/102)
