### ISSUE TITLE
Reduce the number of URLs to configure in setup

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/msupply-cold-chain#249]
**Is your feature request related to a problem? Please describe.**
I've just made two separate errors in typing the URL, and then copied and pasted the error four times.
It's taken some time to correct them all.

**Describe the solution you'd like**
Please can we have just a server URL field, with the four endpoints derived from it.

**Comment by adamdewey** [comment]
Doooonnee 🔥

**Comment by AnushaUp** [comment]
Tested and Passed👌
