### ISSUE TITLE
CCA Sync stops during server backup - tablet needs to be restarted

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/msupply-cold-chain#252]
**Describe the bug**
Reports from BES are that CCA sync stops during the server backup period. 

And, to make matters worse, sync cannot be re-initiated until the tablet is restarted. 

>  we have noted a couple of things. For the test facility which is *******, the tablet stops sync automatically around 10-11pm daily. We saw this yesterday and today as well. In both instances we had to restart the tablet and sync started working.

**To Reproduce**
1. Set up cold chain server with CCA
2. Set up server backups
3. Wait until backup starts - CCA should stop syncing
4. CCA sync will not resume until tablet is restarted
5. **Closing and re-opening app does not resolve the issue (apparently)**

**Expected behavior**
Sync should resume once backup has completed. 

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Tab A8
 - OS: Android 13
 - Version V0.5.3

**Additional context**
- The tablet is on meMDM
- Client backups occur at 10pm
- Tablet is checked at 9am the next morning and is still not syncing

**Comment by AnushaUp** [comment]
I tried with` fiji moh` datafile and cannot recreate the issue on the latest installer(v0.5.6). PASSED
