### ISSUE TITLE
Keep the app awake

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/msupply-cold-chain#255]
**Is your feature request related to a problem? Please describe.**
If left unattended for a couple of days, the app will close and stop logging.

Can we have the app stay online without implementing the service?

Related to #144 and this [mobile issue](https://github.com/openmsupply/mobile/issues/4430)

**Describe the solution you'd like**
The app will continue to monitor sensors and upload data if configured to do so.

**Describe alternatives you've considered**
- Battery optimization request to whitelist the app
- manually lock the app to prevent being closed by battery optimisation

**Comment by AnushaUp** [comment]
Tested with running the application for three days(from 30 dec 2023- 2nd jan 2024) without closing it and the application was running smoothly with all the datas logging.
