### ISSUE TITLE
Cook Islands req: Real-time breach alert

### ISSUE THREAD

**Issue by ghost** [openmsupply/msupply-cold-chain#32]
User requested to be alerted in real-time (SMS?) when a breach occurs. 

Their desire is to set a 'Warning level' breach that will alert them when triggered so they can take action before their vaccines are damaged. 

This will be set in addition to the standard 'Damage level' breach.

**Comment by adamdewey** [comment]
Ok, this was created by me - I'm not a ghost, promise

**Comment by joshxg** [comment]
👻

**Comment by adamdewey** [comment]
This is possible via Telegram alerts - not pretty, but possible. So closing this for now

**Comment by adamdewey** [comment]
Wait, I don't have the rights to close this! 

Boo - @mark-prins any chance you have the ability to grant me the magic power?

**Comment by josh-griffin** [comment]
👻

**Comment by adamdewey** [comment]
Omgomgomg!
