### ISSUE TITLE
TESTING: Sensor settings

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/msupply-cold-chain#39]
# Sensor settings tests

## Prerequisites

- BlueMaestro Tempo Disc sensor(s). 
- Tempo Plus 2 app (available on Google Play Store).

## Test cases

- [ ] `Sensor settings page`:
  - [ ] Title:
    - [ ] Page has title `Sensor Settings`.
  - [ ] `AVAILABLE SENSORS` list:
    - [ ] Heading:
      - [ ] List has heading `AVAILABLE SENSORS`.
    - [ ] List:
      - [ ] Sensor list includes all active sensors.
      - [ ] All sensors are listed by name.
      - [ ] Selecting a sensor navigates to `Sensor detail` page (see below).
  - [ ] `Options` list:
    - [ ] Heading:
      - [ ] List  has heading `OPTIONS`.
    - [ ] `Logging interval` row:
      - [ ] Page has pressable `Logging interval` row.
      - [ ] TODO
  - [ ] `FOUND SENSORS` list:
    - [ ] Heading:
      - [ ] List has heading `FOUND SENSORS`. 
    - [ ] List:
      - [ ] Sensor list includes all discoverable sensors.
      - [ ] All sensors are listed by MAC address (e.g. `E7:22:96:DE:56:02`).
      - [ ] Selecting a list entry brings up `Connect with sensor` bottom modal.
  - [ ] `Connect with sensor` bottom modal:
    - [ ] Title:
      - [ ] Modal has title `Connect with sensor`.
    - [ ] `Blink` button:
      - [ ] Modal has button `Blink`.
      - [ ] If sensor is in-range and has power, pressing `Blink` button causes selected sensor to blink.
      - [ ] If sensor is out-of-range or has no power, pressing `Blink` button times out after "reasonable" delay (no more than ~30s).
    - [ ] `Start logging from` date/time selector:
      - [ ] Modal has `Start logging from` date/time selector.
      - [ ] `Start logging from` date is initialised to current date (`DD/MM/YYY`).
      - [ ] `Start logging from` time is initialise to current time (`HH:MM`).
      - [ ] `Start logging from` date calendar icon brings up date selection widget.
      - [ ] Selecting date in date selection widget updates `Start logging from` date.
      - [ ] `Start logging from` time calendar icon brings up time selection widget.
      - [ ] Selected time in time selection widget updates `Start logging from` time.
    - [ ] `OK` button:
      - [ ] Modal has `OK` button.
      - [ ] Pressing `OK` button closes modal.
      - [ ] Pressing `OK` button causes `Updating...` pop-up to display on screen (see below):
      - [ ] Pressing `OK` button causes sensor to become visible under `AVAILABLE SENSORS` list (see above).
      - [ ] Pressing `OK` button causes sensor to become visible in `Sensors` screen.
    - [ ] `Cancel` button:
      - [ ] Modal has `Cancel` button.
      - [ ] Pressing `Cancel` button closes modal. 
      - [ ] No changes are applied on `Cancel`.
      - [ ] Reopening modal after cancellation resets `Start logging from` date.
      - [ ] Reopening modal after cancellation resets `Start logging from` time.
    - [ ] `Updating...` pop-up:
      - [ ] User cannot perform any actions while pop-up is displayed.
      - [ ] Pop-up closes after "reasonable" delay (no more than ~30s).

- [ ] `Sensor detail page`:
  - [ ] Heading:
    - [ ] Page has heading `Sensor detail`.
  - [ ] `Blink` row:
    - [ ] Page has pressable `Blink` row.
    - [ ] If sensor is in-range and has power, pressing `Blink` button causes selected sensor to blink and "Sensor blink successful" toast is displayed at bottom of page.
    - [ ] If sensor is out-of-range or has no power, pressing `Blink` button times out after "reasonable" delay (no more than ~30 seconds) and "Sensor blink unsuccessful" toast is displayed at bottom of page
  - [ ] `Download` row:
    - [ ] Page has pressable `Download` row.
    - [ ] If sensor is in-range and has power, pressing `Download` button causes temperature logs from sensor to be downloaded and "Sensor download successful" toast to be displayed at bottom of page.
    - [ ] If sensor is in-range and has power, pressing `Download` button causes temperature logs from sensor to be downloaded and displayed in `Sensors` page.
     - [ ] If sensor is in-range and has power, pressing `Download` button causes temperature logs from sensor to be downloaded and displayed in temperature log table (see https://github.com/openmsupply/msupply-cold-chain/issues/51).
    - [ ] If sensor is out-of-range or has no power, pressing `Download` button times out after "reasonable" delay (no more than ~30 seconds) and "Sensor download unsuccessful" toast is displayed at bottom of page
  - [ ] `SENSOR DETAILS` list:
    - [ ] Heading:
      - [ ] List has heading `SENSOR DETAILS`.
    - [ ] List:
      - [ ] List includes sensor MAC address (e.g. `E7:22:96:DE:56:02`).
      - [ ] List includes sensor battery level (e.g. `81%`).
  - [ ] `EDIT SENSOR DETAILS` list:
    - [ ] Heading:
      - [ ] List has heading `EDIT SENSOR DETAILS`.
    - [ ] `Sensor name` row:
      - [ ] List has pressable `Sensor name` row.
      - [ ] Pressing `Sensor name` row opens `Edit sensor name` modal.
    - [ ] `Log interval` row:
      - [ ] List has pressable `Log interval` row.
      - [ ] Pressing `Log interval` row opens `Edit log interval` modal.
  - [ ] `Edit sensor name` modal:
    - [ ] Title:
      - [ ] Modal has title `Edit sensor name`.
    - [ ] Text field:
      - [ ] Modal has editable text field populated with sensor name.
      - [ ] Text field is editable.
    - [ ] `OK` button:
      - [ ] Modal has `OK` button.
      - [ ] Pressing `OK` button closes modal.
      - [ ] Pressing `OK` button updates sensor name.
    - [ ] `Cancel` button:
      - [ ] Modal has `Cancel` button.
      - [ ] Pressing `Cancel` button closes modal.
      - [ ] Pressing `Cancel` button does not update sensor name.
  - [ ] `Edit log interval` modal:
    - [ ] Title:
      - [ ] Modal has title `Edit log interval`.
    - [ ] Text field:
      - [ ] Modal has non-editable text field populated with sensor log interval (e.g. `15 (Minutes)`).
    - [ ] Slider:
      - [ ] Modal has draggable slider initialised with current log interval.
      - [ ] Slider is draggable.
      - [ ] On dragging slider to the right, log interval text field is increased.
      - [ ] On dragging slider to the left, log interval text field is decreased.
    - [ ] `OK` button:
      - [ ] Modal has `OK` button.
      - [ ] Pressing `OK` button closes modal.
      - [ ] Pressing `OK` button causes `Updating...` pop-up to display on screen (see below).
      - [ ] Pressing `OK` button causes log interval to update to value displayed in text field.
    - [ ] `Cancel` button
      - [ ] Modal has `Cancel` button.
      - [ ] Pressing `Cancel` button closes modal.
      - [ ] Pressing `Cancel` button does not update sensor name.
    - [ ] `Updating...` pop-up:
      - [ ] User cannot perform any actions while pop-up is displayed.
      - [ ] Pop-up closes after "reasonable" delay (no more than ~30s).

**Comment by adamdewey** [comment]
Leaving testing to the QA team..
