### ISSUE TITLE
TESTING: Temperature breach settings

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/msupply-cold-chain#49]
# Temperature breach settings tests

The context for this set of tests are for the settings related to temperature breach configurations.

## Setup

- Have the app installed

## Test cases

- [ ] A hot consecutive breach temperature threshold cannot cross over into the cold consecutive breach thresholds
- [ ] A cold consecutive breach temperature threshold cannot cross over into the hot consecutive breach thresholds
- [ ] A hot cumulative breach temperature threshold cannot cross over into the cold cumulative breach thresholds
- [ ] A cold cumulative breach temperature threshold cannot cross over into the hot cumulative breach thresholds
- [ ] Durations of any breach threshold cannot be < 1
- [ ] configurations are saved between app restarts

**Comment by Chris-Petty** [comment]
## Result: Fail

I'll make an issue.

## Test cases

- [ ] A hot consecutive breach temperature threshold cannot cross over into the cold consecutive breach thresholds **Fail: I can set hot breach temp to be lower than cold breach**
- [ ] A cold consecutive breach temperature threshold cannot cross over into the hot consecutive breach thresholds **Fail: I can set cold breach temp to be higher than hot breach**
- [ ] A hot cumulative breach temperature threshold cannot cross over into the cold cumulative breach thresholds **Fail: I can set hot breach temp to be lower than cold breach**
- [ ] A cold cumulative breach temperature threshold cannot cross over into the hot cumulative breach thresholds **Fail: I can set cold breach temp to be higher than hot breach**
- [x] Durations of any breach threshold cannot be < 1
- [x] configurations are saved between app restarts
