### ISSUE TITLE
TESTING: Temperature breaches

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/msupply-cold-chain#50]
# Temperature breaches tests

The context for this testing template is tests related to creating temperature breaches.

## Setup

- Have at least two sensors connected with the app. We should be checking from the initial startup.

### Consecutive breaches
- [ ] When a temperature breach occurs, the app displays the temperature breach
- [ ] When a temperature breach occurs, it is recorded with the correct starting timestamp
- [ ] When a temperature breach finishes, it is recorded with the correct ending timestamp
- [ ] Turn the device+app off while not having a temperature breach, yet. Then, place the sensor in a place where the temperature breach will occur. After awhile, turn the device+app back on. The app should have created a breach for the sensor.
    - [ ] Do the above, while you have one sensor NOT being in breach
    - [ ] Do the above, while you have BOTH sensors being in breach
- [ ] Turn the device+app off while not having a temperature breach, yet. Then, place the sensor in a place where the temperature breach will occur. Without turning the app back on, place the sensor BACK in a position where a breach is NOT occurring. The app should have created a breach for the sensor, but will not CURRENTLY be in breach.
    - [ ] Do the above, while you have one sensor NOT being in breach
    - [ ] Do the above, while you have BOTH sensors being in breach

**Comment by adamdewey** [comment]
Leaving testing to the QA team..
