### ISSUE TITLE
Battery level shows inconsistent Percent value at starting

### ISSUE THREAD

**Issue by ArpitaSussol** [openmsupply/msupply-cold-chain#52]
## Describe the bug

Battery level shows inconsistency in percent value at very start

### To reproduce

1. Go to Settings -> Sensor
2. Under found sensor section, select valid sensor
3. Scroll through available sensor section and choose selected ensor
4. Check Sensor's battery level under Sensor details section
5. See Error. At start it shows battery level as 10% and after few seconds change to original value

https://user-images.githubusercontent.com/58979436/115022330-f6783980-9edc-11eb-829e-54c0538349f0.mp4

### Expected behaviour

Rather it should show N/A at the time of configuring and assigning value to sensor's battery than wrong percent value.

### Proposed Solution

TBD

### Version and device info

- App version:  V0.0.3 rc1
- Tablet model: Samsung
- OS version: 8.1

### Additional context

Think this is very unlikely to occur. However, if it does, then no breaches would ever be created for the sensor which is quite bad.

**Comment by mark-prins** [comment]
unable to reproduce
