### ISSUE TITLE
Section(Log interval or Hot breach/cold breach duration)  is not showing duration label

### ISSUE THREAD

**Issue by ArpitaSussol** [openmsupply/msupply-cold-chain#56]
## Describe the bug

Section(Log interval or Hot breach/cold breach duration)  is not showing number count

### To reproduce

1. Install Cold Chain App
2. At first it will ask different permission, deny each permission
3. Start the App, and go to Log interval section or Hot Breach/Cold Breach duration section
4. See Error. Duration's number(as label) is not showing
5. Reinstall the app. this time allow each permission
6. Start the App, and go to Log interval section or Hot Breach/Cold Breach duration section
7. See Error. Duration's number(as label) is still not showing

https://user-images.githubusercontent.com/58979436/115201379-fe222300-a114-11eb-8fdb-0ae758caed7f.mp4

### Expected behaviour

Label for minute should keep on showing. I tried cleaning storage data as well reinstalling few times but still couldn't able to see that label.
![Screen Shot 2021-04-19 at 1 44 43 PM](https://user-images.githubusercontent.com/58979436/115201814-7557b700-a115-11eb-8041-35a3cfbb28c0.png)

### Proposed Solution

TBD

### Version and device info

- App version:  V0.0.3 rc1
- Tablet model: Samsung
- OS version: 8.1

### Additional context

N/A

**Comment by Chris-Petty** [comment]
Tested, fixed in 0.0.3-rc9 (if not earlier!)
