### ISSUE TITLE
sort out keystore

### ISSUE THREAD

**Issue by joshxg** [openmsupply/msupply-cold-chain#58]
- There was a keystore created for deploying/upgrading to Liberia, I think.
- I was not able to build with that keystore, kept saying it was malformed
- I have since created a new keystore which allowed me to build
- I don't know what we're doing with keystores now 🤷

**Comment by Chris-Petty** [comment]
😢 bizarre. I've dm'd you the deets/keystore I made for Liberia.

New keystore would mean Liberia and Cook islands will have to fully reinstall app to upgrade I think.

**Comment by Chris-Petty** [comment]
@joshxg any luck with this so far?

**Comment by joshxg** [comment]
Oh yup I recloned and it worked
