### ISSUE TITLE
app is not passively connecting with sensors

### ISSUE THREAD

**Issue by joshxg** [openmsupply/msupply-cold-chain#78]
I started the app and connected with sensors and no temperatures are downloaded!

**Comment by richardmoizeau** [comment]
@joshxg, as per our discussion, this should be treated as a high priority (ideally monday next but... well, if you can right ? Don't hurt me...)

**Comment by joshxg** [comment]
@richardmoizeau I made this issue for a bug I found on the development branch. It was not present on the release version so I am not sure if we are aligned on this problem

**Comment by joshxg** [comment]
@richardmoizeau 

Are the actual temperature logs being recorded, and the only issue is that the app says "4 days ago" when in fact it was more recent than that?

**Comment by richardmoizeau** [comment]
Just downloaded logs from one of the tablet and the "last log date" is aligned with what the tablet is showing "4 days ago". However, it seems that the chart is showing the latest record
![Uploading IMAGE 2021-05-11 12:26:41.jpg…]()
