### ISSUE TITLE
V1 Chart Improvements

### ISSUE THREAD

**Issue by andreievg** [openmsupply/msupply-cold-chain#8]
<img width="621" alt="Screen Shot 2020-09-17 at 12 15 47 PM" src="https://user-images.githubusercontent.com/26194949/93404942-b79aea80-f8df-11ea-949b-0ee9a790caf0.png">

<img width="371" alt="Screen Shot 2020-09-17 at 12 14 49 PM" src="https://user-images.githubusercontent.com/26194949/93405155-5a536900-f8e0-11ea-9b27-355a60cab8d0.png">

<img width="626" alt="Screen Shot 2020-09-17 at 12 25 00 PM" src="https://user-images.githubusercontent.com/26194949/93405825-2d07ba80-f8e2-11ea-9612-1d523ee5d746.png">

dot and line indicates 'average', don't have to use dot (it might not make sense to the user)

<img width="377" alt="Screen Shot 2020-09-17 at 12 34 16 PM" src="https://user-images.githubusercontent.com/26194949/93405813-237e5280-f8e2-11ea-9fdf-35faf5763485.png">
<img width="430" alt="Screen Shot 2020-09-17 at 12 34 03 PM" src="https://user-images.githubusercontent.com/26194949/93405817-28430680-f8e2-11ea-9576-17d651d5680b.png">
<img width="445" alt="Screen Shot 2020-09-17 at 12 33 52 PM" src="https://user-images.githubusercontent.com/26194949/93405819-28db9d00-f8e2-11ea-9284-5dc6b1c89ade.png">

```JS
const SQL_GET_CHART_DATA = ({
  numberOfDataPoints,
  sensorId,
  fromTs = moment().subtract(3, 'days').unix(),
  toTs = moment().unix(),
}) => {
  // hmm.. might need to return interval (for UI), in that case should be passed to this SQL builder
  const interval = (toTs - fromTs) / numberOfDataPoints;
  console.log('dreiYow', fromTs, toTs);
  return `
WITH RECURSIVE
  xPoints(fromTs, toTs, interval) as (
    SELECT 
      ${fromTs} fromTs, 
      ${fromTs + interval} toTs, 
      ${interval} interval
  UNION ALL
  SELECT 
    toTs fromTs, 
    toTs + interval toTs, 
    interval 
  FROM 
    xPoints 
  LIMIT ${numberOfDataPoints} )

SELECT 
  ((xPoints.toTs + xPoints.fromTs) / 2) timestamp, 
  AVG(temperature) temperature, 
  MAX(temperature) ymax, 
  MIN(temperature) ymin 
FROM 
  xPoints 
LEFT JOIN (
  SELECT 
    timestamp - logInterval fromTs, 
    timestamp toTs, 
    temperature 
  FROM 
    temperatureLog 
  WHERE 
    sensorId = '${sensorId}' AND
    timestamp >= ${fromTs} AND
    timestamp <= ${toTs} 
  ) AS sensorTemperatureLog
ON
  (xPoints.toTs >= sensorTemperatureLog.fromTs OR xPoints.toTs >= sensorTemperatureLog.toTs)  
  AND
  (xPoints.fromTs <= sensorTemperatureLog.fromTs OR xPoints.fromTs <=  sensorTemperatureLog.toTs)
GROUP BY timestamp`;
};

const SQL_GET_CHART_TIMESTAMPS = ({
  sensorId,
  fromTs = moment().subtract(3, 'days').unix(), // set to 0 to get range of timestamps for sensor
  toTs = moment().unix(),
  enforceToTs = true, // return toTs rather then DB query
  enforceFromTs = false, // return fromTs rather then DB query
}) => `
SELECT 
  CASE
    WHEN ${enforceFromTs ? 1 : 0} = 1 then ${fromTs}
    ELSE MIN(timestamp)
  END minChartTimestamp,
  CASE
    WHEN ${enforceToTs ? 1 : 0} = 1 then ${toTs}
    ELSE MAX(timestamp)
  END maxChartTimestamp
FROM
  temperatureLog
WHERE 
  sensorId = '${sensorId}' AND
  timestamp >= ${fromTs} AND
  timestamp <= ${toTs}
`;

```

note there will be null values so current 'minTemp' and 'maxTemp' calculation needs to ignore it

```JS
export const ChartGradient = ({
  max,
  min,
  offsets = [],
  defaultOpacity = 1,
  id = CONSTANTS.DEFAULT_ID,
}) => {
  const range = max - min;

  if (range === 0) return null;

  const getOffsetPercentage = offset => `${((max - offset) / range) * 100}%`;
  return (
    <Defs>
      <LinearGradient
        id={id}
        x1={CONSTANTS.X1}
        y1={CONSTANTS.Y1}
        x2={CONSTANTS.X2}
        y2={CONSTANTS.Y2}
      >
        {offsets.map(({ offset, color, opacity }) => (
          <Stop
            offset={getOffsetPercentage(offset)}
            stopColor={color}
            stopOpacity={opacity ?? defaultOpacity}
          />
        ))}
      </LinearGradient>
    </Defs>
  );
};

```

```JS
const offsets = [
    { offset: 8, color: COLOUR.DANGER },
    { offset: 8, color: COLOUR.PRIMARY },
    { offset: 2, color: COLOUR.PRIMARY },
    { offset: 2, color: COLOUR.DANGER },
];
```

```JS
<ChartGradient 
    min={avgMinTemp} 
    max={avgMaxTemp} 
    offsets={offsets} 
    id={'avgChartGradient'} />

<ChartGradient
    min={minTemp}
    max={maxTemp}
    offsets={offsets}
    opacity={0.5}
    id={'minMaxChartGradient'}
/>

<VictoryArea
    data={data}
    style={{ data: { fill: 'url(#minMaxChartGradient)' } }}
    x={CHART.X_KEY}
    y0={CHART.Y_MIN_KEY}
    y={CHART.Y_MAX_KEY}
    interpolation={'step'}
/>

<VictoryLine
    data={data}
    x={CHART.X_KEY}
    y={CHART.Y_KEY}
    interpolation={CHART.INTERPOLATION}
    style={{ data: { stroke: 'url(#avgChartGradient)' } }}
/>

<VictoryScatter
    data={data}
    x={CHART.X_KEY}
    y={CHART.Y_KEY}
    size={3}
    style={{
        data: {
        fill: ({ datum: { temperature } }) =>
            2 < temperature || temperature < 8 ? COLOUR.PRIMARY : COLOUR.DANGER,
        },
    }}
/>
```

**Comment by joshxg** [comment]
@andreievg 

badass

Do you know if the 'blockyness' can be changed much?

**Comment by andreievg** [comment]
@joshxg, thanks, yay I got to do some dev work

hmm can do a bar chart instead of area, should be able to customise it more then just step interpolation of area  (I think it would require calculating bar width from number of data points and width, if we want them joined), also can do different interpolation for the area chart (possibility of overlap though), for some reason I kind of liked the blocky view, with non randomised data it looks pretty nice imo.

Anyways that's the best I could come up with in the timeframe that I want to commit to the task (it's fun stuff though). Happy to look at other options, but I feel this should do the trick for most use cases.

Only addition would be a legend (to tell the user what the interval is for a 'block'

**Comment by andreievg** [comment]
Ohh an happy to consider alternative, although with reason for alternative in mind (reason for this version btw, was to show more statistics then just the average, allow for dynamic log interval i a simple straight forward way, use fixed number of data points regardless of the amount of data, show gaps in data if they exist).

**Comment by joshxg** [comment]
Wonder if you can "fade" each of the colours out - having a more fluid transform from the red->blue, and possible if you made the area 100% height, you could fade the top and bottom into 'transparent'.. hope that makes sense..?

**Comment by joshxg** [comment]
Oh - I just got a bit confused by the colours with hot and cold, how come the bottom ones are hot also?

**Comment by andreievg** [comment]
Hmm, I think i am still confused about colours of breach types. 

Might need to make some options for the team to vote one, i.e (hot to good to cold)

Orange
Green
Blue

Orange
White 
Blue 
(which I think is what you had with the original gradient)

I guess we can play around with those towards the very end of V1.

As for the fade. Could be an option, although I kind of wanted to make those boxes as definitive as possible (i.e show exactly what the max and min exposure was). And then the line shows the average, which could indicate, that in that time period, temperature was leaning towards max or min.

**Comment by andreievg** [comment]
I have some data from real sensor (not saying this data is reflective of typical fridge data btw, but still another perspective)
<img width="275" alt="Screen Shot 2020-09-17 at 6 05 00 PM" src="https://user-images.githubusercontent.com/26194949/93426619-84bd1a80-f910-11ea-86ea-d6dca893f68d.png">

**Comment by mark-prins** [comment]
Unsure how to categorise this change. @andreievg @joshxg any suggestions?
In or out for the upcoming release? v0.3.0 instead? backlog?

**Comment by joshxg** [comment]
I think backlog. I would love to get something in but with the current priorities I think it can either be done when someone has time to do something fun or when we get some more customers using the app

**Comment by adamdewey** [comment]
Chart is good enough for now, most close analysis will be done in the logs or on the server, so closing
