### ISSUE TITLE
ability to type the temperature when configuring temperature details instead of (or in addition) to the existing sliders

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/msupply-cold-chain#86]
When configuring temperature breach settings, not easy to select a specific duration and temperature using the sliders. Would be nice to be able to type the number. 
Another solution would be to only allow the duration to 120 minutes but would still take a few trials to select the right duration :-)

**Comment by Chris-Petty** [comment]
@joshxg sorry I can't believe we forgot to prioritise this one 🤣 .

I think you must have improved it for the temperature thresholds, as they seem to be on a scale of -30 to +55. That's ok, still a bit of trial and error trying to configure. Text input with numeric keypad would be an awesome alternative. Also would be super slick if the number updated while you moved the slider, so you know where you're at (and can do it in one go).

Still really painful for duration- scale is 1 to 600. For cook islands we basically want it to be around 5mins generally. Really hard to set consistently at the mo!

**Comment by joshxg** [comment]
Have done a very minimal implementation which will at least allow us to be precise when configuring even though there is still room to improve the UX.

**Comment by Chris-Petty** [comment]
Tested, fixed in 0.0.3-rc9
