### ISSUE TITLE
Sensor Row alignments tweaks

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/msupply-cold-chain#89]
- Breach widgets with different amounts of digits move the icon different amounts. I'd suggest making both the text and the icon flex 0, align with space-between. Never know exactly what to set till you play with it though 😄.
- should the white row separator go all the way across?
- The right chevron button on the right of each row gets pushed off screen on rows with breach. (Could also be getting pushed by the text, not sure).
- Temperature ranges that are completely negative look a bit funny with hyphens beside minus signs. Maybe use the word "and"? 
- x-axis labels in middle of some charts? (Being chart related I can see this point could be it's own issue heh). Maybe redundant if going to make consistent charts between mcc and mobile in #71 ?

![image](https://user-images.githubusercontent.com/7684221/115485737-67d33600-a2a9-11eb-9ce5-36eb28a7e342.png)

**Comment by Chris-Petty** [comment]
A few more samples:

Decimal temperature affecting icon placement:

![Screenshot_2021-05-13-14-01-54-326](https://user-images.githubusercontent.com/7684221/118068071-d6fa0100-b3f5-11eb-9489-0dd816d421c9.jpeg)

I'm quite certain this is caused by the difference in widths of the sensor names + battery level digits.
![Screenshot_2021-05-13-14-06-58-944](https://user-images.githubusercontent.com/7684221/118068078-d9f4f180-b3f5-11eb-8d88-9ad6c17c7ca4.jpeg)

**Comment by mark-prins** [comment]
Unable to reproduce
- x-axis labels in middle of some charts
- Right chevron pushed off the page

Removed from UI and no longer needed to fix?
- white row separator
- cold cumulative breach wording

**Comment by mark-prins** [comment]
Noticed the x-axis happening on a chart which has positive and negative values in it.
There is a [relevant issue](https://github.com/FormidableLabs/victory/issues/1113) which means it isn't just us.

**Comment by Chris-Petty** [comment]
> Noticed the x-axis happening on a chart which has positive and negative values in it.
> There is a [relevant issue](https://github.com/FormidableLabs/victory/issues/1113) which means it isn't just us.

Ah I see! Good find
