### ISSUE TITLE
User can only acknowledge bottom most sensor breaches

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/msupply-cold-chain#9]
"As I reported earlier, only the bottom sensor on the screen allows a user to acknowledge a temperature break. You can get to the same screen for the other sensors as well, but when you click acknowledge, you are taken back to the main screen and nothing happens - just as if you had clicked on cancel. All three tablets behave in the same way."

MCC version: 0.0.2

This repo could use an issue templates, labels etc. overhaul sometime soon?

**Comment by richardmoizeau** [comment]
@joshxg, high priority, May 10th, don't hurt me.

**Comment by Chris-Petty** [comment]
Tested on 0.3.0-rc4, seems fixed!
