### ISSUE TITLE
Splash screen scales up when the screen orientation is changed

### ISSUE THREAD

**Issue by joshxg** [openmsupply/msupply-cold-chain#97]
When opening the app in landscape, the splash screen svg scales and gets cut off. Also the mSupply man is just too big

**Comment by mark-prins** [comment]
Improved with #140 - is that enough? 
The guy is still pretty big - though he's nicely centred now, so looks ok to me. Only other way I can see of improving would be to remove the gradient and have a solid colour background - easy enough, just not as fancy.

**Comment by joshxg** [comment]
Yeah I think it looks a lot better now. I had a quick look around and it seems we might need a different splash for horizontal and vertical which would require more java fiddling and so this can go straight into the too hard basket
